# Carte del gioco "La Linea del Tempo"

MAIN_CARDS = [
    {"id": 1, "fase": "LE ORIGINI", "titolo": "Il primo sguardo",
     "domanda": "Qual è il primo ricordo che hai legato al lavoro o agli adulti che lavoravano?",
     "extra": "Se fosse un'immagine, cosa vedresti?"},
    {"id": 2, "fase": "LE ORIGINI", "titolo": "La voce che ti ha guidato",
     "domanda": "C'è stata una persona che ha influenzato il tuo modo di vedere il futuro?",
     "extra": "Che frase le attribuiresti oggi?"},
    {"id": 3, "fase": "LE ORIGINI", "titolo": "La prima scelta",
     "domanda": "Qual è stata la prima decisione importante che hai preso per il tuo percorso?",
     "extra": "La rifaresti allo stesso modo?"},
    {"id": 4, "fase": "L'IMMERSIONE", "titolo": "Lo zaino",
     "domanda": "Cosa ti sei portato/a dall'infanzia o dalla scuola?",
     "extra": "Un talento, una paura o un valore?"},
    {"id": 5, "fase": "L'IMMERSIONE", "titolo": "Il primo impatto",
     "domanda": "Ricordi il tuo primo vero incontro con il mondo del lavoro?",
     "extra": "Cosa ti ha sorpreso di più?"},
    {"id": 6, "fase": "L'IMMERSIONE", "titolo": "Il mondo reale",
     "domanda": "Qual è stata la differenza più grande tra come immaginavi il lavoro e come lo hai trovato?",
     "extra": "Meglio o peggio?"},
    {"id": 7, "fase": "CONSOLIDAMENTO", "titolo": "Il cambiamento",
     "domanda": "Hai mai cambiato punto di vista e rimesso in discussione tutto?",
     "extra": "Racconta un importante cambio di rotta."},
    {"id": 8, "fase": "CONSOLIDAMENTO", "titolo": "Dentro al ruolo",
     "domanda": "Quando hai iniziato a sentirti davvero \"al tuo posto\"?",
     "extra": "Cosa stavi costruendo in quel periodo?"},
    {"id": 9, "fase": "CONSOLIDAMENTO", "titolo": "La realizzazione",
     "domanda": "In quale fase ti sei sentito/a più energico/a e realizzato nel lavoro?",
     "extra": "Perché proprio quella?"},
    {"id": 10, "fase": "L'EVOLUZIONE", "titolo": "La crisi utile",
     "domanda": "Hai mai rimesso in discussione il tuo percorso?",
     "extra": "Cosa ti ha insegnato quel momento?"},
    {"id": 11, "fase": "L'EVOLUZIONE", "titolo": "Oggi",
     "domanda": "Cosa ti dà motivazione nel lavoro oggi?",
     "extra": "E cosa invece te ne toglie?"},
    {"id": 12, "fase": "L'EVOLUZIONE", "titolo": "Chi sei ora",
     "domanda": "In questo momento, che tipo di professionista senti di essere?",
     "extra": "Una parola per descriverti."},
    {"id": 13, "fase": "L'EREDITÀ", "titolo": "Il lascito",
     "domanda": "Cosa ti piacerebbe lasciare alle persone con cui lavori?",
     "extra": "Un modo di fare, un valore, un esempio."},
    {"id": 14, "fase": "L'EREDITÀ", "titolo": "Il domani",
     "domanda": "Guardando avanti, cosa speri di vivere professionalmente?",
     "extra": "Più continuità o più cambiamento?"},
    {"id": 15, "fase": "L'EREDITÀ", "titolo": "Il titolo",
     "domanda": "Se la tua vita professionale fosse un film, che titolo avrebbe?",
     "extra": "Genere: drammatico, commedia, avventura…?"},
]

COMMON_CARDS = [
    {"id": 101, "fase": "TERRENI COMUNI", "titolo": "Cinema",
     "domanda": "Qual è il film che ha cambiato la tua vita?",
     "extra": "Un episodio legato a quella pellicola."},
    {"id": 102, "fase": "TERRENI COMUNI", "titolo": "Musica",
     "domanda": "Quali sono i tre dischi che porteresti sull'isola deserta?",
     "extra": "Una storia legata a una canzone."},
    {"id": 103, "fase": "TERRENI COMUNI", "titolo": "Teatro",
     "domanda": "Hai uno spettacolo del cuore?",
     "extra": "Genere: drammatico, commedia?"},
    {"id": 104, "fase": "TERRENI COMUNI", "titolo": "Libri",
     "domanda": "Qual è il tuo libro preferito?",
     "extra": "L'episodio o la frase che ti è rimasta impressa."},
    {"id": 105, "fase": "TERRENI COMUNI", "titolo": "Fumetti",
     "domanda": "Supereroi o altro?",
     "extra": "Più continuità o più cambiamento?"},
    {"id": 106, "fase": "TERRENI COMUNI", "titolo": "Sport",
     "domanda": "Lo sport che ti ha accompagnato.",
     "extra": "Un episodio epico?"},
]

FINAL_CARD = {
    "id": 999, "fase": "CARTA FINALE", "titolo": "Una cosa sola",
    "domanda": "Se dovessi scegliere una sola cosa che racconta il tuo percorso, quale sarebbe?",
    "extra": "Giro di chiusura: cosa porto via da questo cerchio?"
}

ALL_CARDS = MAIN_CARDS + COMMON_CARDS
