# Carte del gioco "La Linea del Tempo"

MAIN_CARDS = [
    {"id": 1, "fase": "LE ORIGINI", "titolo": "Il primo sguardo",
     "domanda": "Qual è il primo ricordo che hai legato al lavoro o agli adulti che lavoravano?",
     "extra": "Se fosse un'immagine, cosa vedresti?",
     "img": "/public/cards/card_1.jpg"},
    {"id": 2, "fase": "LE ORIGINI", "titolo": "La voce che ti ha guidato",
     "domanda": "C'è stata una persona che ha influenzato il tuo modo di vedere il futuro?",
     "extra": "Che frase le attribuiresti oggi?",
     "img": "/public/cards/card_2.jpg"},
    {"id": 3, "fase": "LE ORIGINI", "titolo": "La prima scelta",
     "domanda": "Qual è stata la prima decisione importante che hai preso per il tuo percorso?",
     "extra": "La rifaresti allo stesso modo?",
     "img": "/public/cards/card_3.jpg"},
    {"id": 4, "fase": "L'IMMERSIONE", "titolo": "Lo zaino",
     "domanda": "Cosa ti sei portato/a dall'infanzia o dalla scuola?",
     "extra": "Un talento, una paura o un valore?",
     "img": "/public/cards/card_4.jpg"},
    {"id": 5, "fase": "L'IMMERSIONE", "titolo": "Il primo impatto",
     "domanda": "Ricordi il tuo primo vero incontro con il mondo del lavoro?",
     "extra": "Cosa ti ha sorpreso di più?",
     "img": "/public/cards/card_5.jpg"},
    {"id": 6, "fase": "L'IMMERSIONE", "titolo": "Il mondo reale",
     "domanda": "Qual è stata la differenza più grande tra come immaginavi il lavoro e come lo hai trovato?",
     "extra": "Meglio o peggio?",
     "img": "/public/cards/card_6.jpg"},
    {"id": 7, "fase": "CONSOLIDAMENTO", "titolo": "Il cambiamento",
     "domanda": "Hai mai cambiato punto di vista e rimesso in discussione tutto?",
     "extra": "Racconta un importante cambio di rotta.",
     "img": "/public/cards/card_7.jpg"},
    {"id": 8, "fase": "CONSOLIDAMENTO", "titolo": "Dentro al ruolo",
     "domanda": "Quando hai iniziato a sentirti davvero \"al tuo posto\"?",
     "extra": "Cosa stavi costruendo in quel periodo?",
     "img": "/public/cards/card_8.jpg"},
    {"id": 9, "fase": "CONSOLIDAMENTO", "titolo": "La realizzazione",
     "domanda": "In quale fase ti sei sentito/a più energico/a e realizzato nel lavoro?",
     "extra": "Perché proprio quella?",
     "img": "/public/cards/card_9.jpg"},
    {"id": 10, "fase": "L'EVOLUZIONE", "titolo": "La crisi utile",
     "domanda": "Hai mai rimesso in discussione il tuo percorso?",
     "extra": "Cosa ti ha insegnato quel momento?",
     "img": "/public/cards/card_10.jpg"},
    {"id": 11, "fase": "L'EVOLUZIONE", "titolo": "Oggi",
     "domanda": "Cosa ti dà motivazione nel lavoro oggi?",
     "extra": "E cosa invece te ne toglie?",
     "img": "/public/cards/card_11.jpg"},
    {"id": 12, "fase": "L'EVOLUZIONE", "titolo": "Chi sei ora",
     "domanda": "In questo momento, che tipo di professionista senti di essere?",
     "extra": "Una parola per descriverti.",
     "img": "/public/cards/card_12.jpg"},
    {"id": 13, "fase": "L'EREDITÀ", "titolo": "Il lascito",
     "domanda": "Cosa ti piacerebbe lasciare alle persone con cui lavori?",
     "extra": "Un modo di fare, un valore, un esempio.",
     "img": "/public/cards/card_13.jpg"},
    {"id": 14, "fase": "L'EREDITÀ", "titolo": "Il domani",
     "domanda": "Guardando avanti, cosa speri di vivere professionalmente?",
     "extra": "Più continuità o più cambiamento?",
     "img": "/public/cards/card_14.jpg"},
    {"id": 15, "fase": "L'EREDITÀ", "titolo": "Il titolo",
     "domanda": "Se la tua vita professionale fosse un film, che titolo avrebbe?",
     "extra": "Genere: drammatico, commedia, avventura...?",
     "img": "/public/cards/card_15.jpg"},
]

COMMON_CARDS = [
    {"id": 101, "fase": "TERRENI COMUNI", "titolo": "Cinema",
     "domanda": "Qual è il film che ha cambiato la tua vita?",
     "extra": "Un episodio legato a quella pellicola.",
     "img": "/public/cards/card_101.jpg"},
    {"id": 102, "fase": "TERRENI COMUNI", "titolo": "Musica",
     "domanda": "Quali sono i tre dischi che porteresti sull'isola deserta?",
     "extra": "Una storia legata a una canzone.",
     "img": "/public/cards/card_102.jpg"},
    {"id": 103, "fase": "TERRENI COMUNI", "titolo": "Teatro",
     "domanda": "Hai uno spettacolo del cuore?",
     "extra": "Genere: drammatico, commedia?",
     "img": "/public/cards/card_103.jpg"},
    {"id": 104, "fase": "TERRENI COMUNI", "titolo": "Libri",
     "domanda": "Qual è il tuo libro preferito?",
     "extra": "L'episodio o la frase che ti è rimasta impressa.",
     "img": "/public/cards/card_104.jpg"},
    {"id": 105, "fase": "TERRENI COMUNI", "titolo": "Fumetti",
     "domanda": "Supereroi o altro?",
     "extra": "Più continuità o più cambiamento?",
     "img": "/public/cards/card_105.jpg"},
    {"id": 106, "fase": "TERRENI COMUNI", "titolo": "Sport",
     "domanda": "Lo sport che ti ha accompagnato.",
     "extra": "Un episodio epico?",
     "img": "/public/cards/card_106.jpg"},
]

FINAL_CARD = {
    "id": 999, "fase": "CARTA FINALE", "titolo": "Una cosa sola",
    "domanda": "Se dovessi scegliere una sola cosa che racconta il tuo percorso, quale sarebbe?",
    "extra": "Giro di chiusura: cosa porto via da questo cerchio?",
    "img": "/public/cards/card_final.jpg"
}

ALL_CARDS = MAIN_CARDS + COMMON_CARDS
